= LRA annotation checker Maven plugin

The purpose of this Maven plugin is to provide verification of correct
usage of LRA annotation used in the project.
Plugin scans LRA annotation on your project and highlights the usage
which contradicts to LRA specification
https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/0009-LRA


== Motivation: why to use this in your project

Let's introduces few inaccuracies this plugin can help to discover

* you use annotation `@Compensate` but forget to provide the complementary
  `@Path` annotation declaring the JAX-RS endpoint to contact when the LRA fails
* you defines the endpoint with LRA annotation `@Forget` defines with `@Path`
  to be called by LRA coordinator when it's not needed to store the state
  for case of compensation. But you forget that the endpoint will be called
  with HTTP `DELETE` and the `@DELETE` JAX-RS annotation misses at the method
* ...


== How to use

The plugin defines goal `check`, by default it's run at phase `process-classes`.

Plugin parameters are

`paths`::
  list of file system paths to be scanned for classes using LRA annotations. If exists the provided path
  has to be either pointing to a directory or to a jar file. If not provided the value default value
  is path to `target/classes` (a.k.a `${project.build.directory}`).
`failWhenPathNotExist`::
  define if plugin fails (throws exception) when some of the provided `paths` param is an non-existing path.
  expected value is boolean `true` or `false`. The default value is `true`.

=== Usage example

Add the following to your project `pom.xml`

```xml
<build>
  <plugins>
    <plugin>
      <groupId>io.narayana</groupId>
      <artifactId>lra-annotation-checker-maven-plugin</artifactId>
      <version>1.0.0.Alpha1-SNAPSHOT</version>
      <executions>
        <execution>
          <goals>
            <goal>check</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```

== How to build

Compile with Maven.

[source,bash]
----
mvn clean install
----

== How to release

Release is performed to https://repository.jboss.org/nexus/[JBoss Nexus].

Credentials for release needs to be setup in the `~/.m2/settings.xml` (or settings defined with `-s` parameter)
where you link the repository id `jboss-releases-repository` with the username/password.

```xml
<server>
    <id>jboss-releases-repository</id>
    <username>[username]</username>
    <password>[password for jboss nexus connection]</password>
</server>
```

As the next step run the `mvn release` and proceed standard
http://maven.apache.org/maven-release/maven-release-plugin/usage.html[steps for maven release plugin].

* `git checkout main; git fetch upstream main; git rebase upstream/main; git push upstream main`
* `mvn javadoc:javadoc` - verification that there won't be any javadoc errors during `release:perform`

* `mvn release:clean`
* `mvn release:prepare`
* `mvn release:perform`

Dry run: `mvn release:prepare -DdryRun=true`

