= Narayana LRA annotation checker: Maven plugin

Maven plugin providing build time verification of LRA annotations.

The plugin searches the LRA annotations in your project during *_build time_*,
and highlights the rules that contradicts with the LRA specification of version `1.0`:
https://github.com/eclipse/microprofile-lra/blob/1.0/spec/src/main/asciidoc/microprofile-lra-spec.adoc

== Usage

Add the following to your project `pom.xml`

```xml
<build>
  <plugins>
    <plugin>
      <groupId>io.narayana</groupId>
      <artifactId>maven-plugin-lra-annotations_1.0</artifactId>
      <version>1.0.0.Beta1</version>
      <executions>
        <execution>
          <goals>
            <goal>check</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```

=== Configuration

The plugin defines the goal `check`, by default it's run at phase `process-classes`.

.Plugin parameters
|====
|Parameter name |Description

|`paths`
|Defines the list of file system paths that will be scanned by plugin.
 The provided path (if exists) has to be pointing to a directory or to a jar file.
 The default value is path to `target/classes` (a.k.a. `${project.build.directory}`).
|`failWhenPathNotExist`
|Defines if plugin fails (throws exception) when some provided `paths` param
 does not exist. It's a boolean value `true` or `false`. The default value is `true`.
|====


== Plugin processing

The plugin verifies if the following is valid in the project

* https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ws/rs/LRA.java#L46[`@LRA` annotation]
 has to be accompanied with one or both annotations `@Compensate` or `@AfterLRA`
* annotations used for non-JAX-RS resources have to be with a valid method signature
** method is `public`
** return type is `void`, `CompletionStage`, `LRAStatus` or `Response`
** there is defined specified parameters which is `(java.net.URI)` or `(java.net.URI, java.net.URI)`
   for most of the annotations, or `(java.net.URI, LRAStatus)` for `AfterLRA`
* JAX-RS resources need to be accompanied with JAX-RS `@Path` annotation
  and one particular HTTP method is required
+
|====
|Annotation name |Required HTTP method
|`@Complete` | `@PUT`
|`@Compensate` | `@PUT`
|`@AfterLRA` | `@PUT`
|`@Leave` | `@PUT`
|`@Status` | `@GET`
|`@Forget` | `@DELETE`
|====
+
* Only one LRA annotation of one type is permitted in one class
  (i.e., for example the class cannot be defined with two `@Complete` annotations)

== How to build

Compile with Maven.

[source,bash]
----
mvn clean install
----

== How to release

Release is performed to https://repository.jboss.org/nexus/[JBoss Nexus].

Credentials for release needs to be setup in the `~/.m2/settings.xml` (or settings defined with `-s` parameter)
where you link the repository id `jboss-releases-repository` with the username/password.

```xml
<server>
    <id>jboss-releases-repository</id>
    <username>[username]</username>
    <password>[password for jboss nexus connection]</password>
</server>
```

As the next step run the `mvn release` and proceed standard
http://maven.apache.org/maven-release/maven-release-plugin/usage.html[steps for maven release plugin].

* `git checkout main; git fetch upstream main; git rebase upstream/main; git push upstream main`
* `mvn javadoc:javadoc` - verification that there won't be any javadoc errors during `release:perform`

* `mvn release:clean`
* `mvn release:prepare`
* `mvn release:perform`

Dry run: `mvn release:prepare -DdryRun=true`
